title: The Criteria Compilation
description: A compilation of recommended acoustical design criteria for different room types.
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
