title: The Criteria Compilation
description: A searchable compilation of recommended noise levels for different room types.
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
